# Generated by Django 3.0.8 on 2020-07-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20200714_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albumcover',
            field=models.ImageField(null=True, upload_to='media/album/images'),
        ),
    ]
