# Generated by Django 3.0.8 on 2020-07-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_album_albumcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumcover',
            field=models.ImageField(null=True, upload_to='media/album/images/'),
        ),
    ]
